# Generated by Django 3.1.7 on 2021-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
